### PR TITLE
upgrade to new analytics-browser SDK

### PR DESCRIPTION
**Pull request by jimmynotjim**
Upgrades the package to the newer [analytics-browser SDK](https://github.com/amplitude/Amplitude-TypeScript) following the direction from the [migration documentation](https://www.docs.developers.amplitude.com/data/sdks/typescript-browser/migration/)

### CODE REVIEW

**Comment by jimmynotjim** [comment]
@maecapozzi I linked this package into our DS package to test my changes but when I run storybook I'm getting really obtuse errors that don't seem to be related to the new SDK but I'm unsure. Is this the correct way to test this package? 

```
unable to close vite server
REPOPATH/node_modules/@storybook/core-server/dist/cjs/build-dev.js:191
    } else if ((_error$compilation = error.compilation) !== null && _error$compilation !== void 0 && _error$compilation.errors) {
                                           ^

TypeError: Cannot read properties of undefined (reading 'compilation')
    at buildDev (REPOPATH/node_modules/@storybook/core-server/dist/cjs/build-dev.js:191:44)

Node.js v18.15.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by maecapozzi** [comment]
@jimmynotjim - how did you link it? Can you provide a code snippet to show what you did?

I set this package up to publish "canary" releases, so you should also be able to test it by installing this version: ` @amplitude/storybook-addon-amplitude@1.0.16--canary.91bb694.0`.

**Comment by jimmynotjim** [comment]
I used `yarn link` in this repo and then ran `yarn link @amplitude/storybook-addon-amplitude` in the package in our private repo. Turns out using the canary build works great though so I think this PR is ready for review.

**Review by maecapozzi — APPROVED** [review]

**Comment by maecapozzi** [comment]
Yeah, I feel like `yarn link` can be kind of sketchy, so I always publish a canary version as well.

**Pull request merged**
